name: Update Wiki

on:
  workflow_dispatch:
  push:
    paths:
      - 'docs/**'
    branches:
      - 'main'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Updating Wiki
      uses: Andrew-Chen-Wang/github-wiki-action@v4
      env:
        WIKI_DIR: docs/
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GH_MAIL: '41898282+github-actions[bot]@users.noreply.github.com'
        GH_NAME: 'github-actions[bot]'
        EXCLUDED_FILES: 'README.md'
        WIKI_PUSH_MESSAGE: '${{ github.event.commits[0].message }}'
